services:
  app:
    image: julixxx23/app-ochoa:latest
    container_name: appochoa
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Variables de negocio — vienen del .env del servidor
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      LOKI_URL: ${LOKI_URL}
      LOKI_USERNAME: ${LOKI_USERNAME}
      LOKI_PASSWORD: ${LOKI_PASSWORD}

      SPRING_PROFILES_ACTIVE: prod

      JAVA_OPTS: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=75.0
        -XX:+ExitOnOutOfMemoryError
        -Djava.security.egd=file:/dev/./urandom
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 3