ALTER TABLE ventas_fel
    MODIFY COLUMN fel_estado ENUM('PENDIENTE', 'CERTIFICADA', 'ERROR', 'ANULADA') NOT NULL DEFAULT 'PENDIENTE';

ALTER TABLE ventas_fel_notas_credito
    MODIFY COLUMN nota_estado ENUM('PENDIENTE', 'CERTIFICADA', 'ERROR') NOT NULL DEFAULT 'PENDIENTE';